### ISSUE TITLE
Insights to hardware connection

### ISSUE THREAD

**Issue by ffd8** [jakkra/FlipDot#1]
Hi @jakkra – this looks amazing and exactly what I need to communicate with my old flipdot bus signs (BROSE brand). Just a small require here or in the readme to include some additional details about the suggested ESP32 + RS485 serial board you'd recommend and how you went about wiring and powering the flipdot module, as there's no photos from the back side. Thanks!

**Comment by jakkra** [comment]
Hi @ffd8 this may not work with your "BROSE brand". The display I'm using is from https://flipdots.com/en/products-services/flip-dot-boards-xy5/ and you control them over RS485. Those filipdots take VCC and the RS485 signals and have the controller embedded on the display. So I only needed to provide power and RS485 signals. This is likely different from yours as those old signs typically don't have a simple controller already and one needs to be built.

**Comment by ffd8** [comment]
Hey @jakkra - thanks for the super fast reply! Rightio – yeah those newer boards seem very well prepared for communication. Nevertheless, my old BROSE do have the original PCB controllers attached and from a [youtube video](https://youtu.be/DZdEKYEQ3sA?si=RZENkHALMKz1SwCm&t=379) (diff display, but similar), made me hopeful that it's possible to tap into it via RS485 (since that's what the original playback boxes used). There's a handful of various ESP32's and RS485 shields - do you have a suggestion of particular ones you had success with?

**Comment by jakkra** [comment]
Any ESP32 devkit should be fine, I prefer the ESP32 official ones. For the RS485 I just use a cheap common one, don't know exact model, but looks like the ones if you google "RS485 adapter".
